### ISSUE TITLE
Messes up

### ISSUE THREAD

**Issue by aentan** [stolksdorf/CleanCSS#22]
```css
p + figure,
p + iframe {
  margin-top : 30px;
}

figure + p,
iframe + p {
  margin-top : 30px;
}

@include media(">=tablet") {
  p + figure,
  p + iframe {
    margin-top : 60px;
  }
  figure + p,
  iframe + p {
    margin-top : 60px;
  }
}
```

turns to

```css
p + iframe {
  margin-top : 30px;
}

iframe + p {
  margin-top : 30px;
}

@include media(">=tablet") {
  p + figure,
  figure + p,

  p + iframe {
    margin-top : 60px;
  }

  iframe + p {
    margin-top : 60px;
  }
}
```
